CREATE DATABASE apariv;

USE apariv;

CREATE TABLE dogs(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(45) NOT NULL,
    breed VARCHAR(45) NOT NULL,
    DOB DATE NOT NULL,
    behaviour TINYTEXT NOT NULL
);

CREATE TABLE adopters(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(45) NOT NULL,
    lastname VARCHAR(100) NOT NULL,
    DNI INT NOT NULL
);